---
- name: Installing Ubuntu application
  apt: "name={{ item }} state=installed"
  with_items:
    - synaptic 
    - unity-tweak-tool 
    - compizconfig-settings-manager
    - gnome-terminal

- name: Gnome and Unity settings
  gsetting: user="{{username}}"
            key="{{item.key}}"
            value="{{item.value}}"
  with_items: "{{ gsettings }}"

  # Install Google's Chrome
- name: "apt | ensure Google linux signing key present"
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: "apt | ensure previous repository for Google Chrome is absent, as Google removed the x86 distribution"
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=absent

- name: "apt | ensure Google chrome repo present, using a workaround for missing x86 distribution"
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"
  register: google_repo

- name: "apt | update cache"
  apt: update_cache=yes
  when: google_repo.changed
  
- name: "apt | ensure Google chrome present"
  apt: name=google-chrome-stable update_cache=yes

# - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
#   shell: ln -s /opt/google/chrome/goole-chrome.desktop /usr/share/applications/google-chrome.desktop
  
- name: Install latest version of "openjdk-6-jdk" ignoring "install-recommends"
  apt:
    name: openjdk-6-jdk
    state: latest
    install_recommends: no

# Install Sublime Text 3
- name: Download sublimetext .deb file
  get_url: "url=https://download.sublimetext.com/sublime-text_build-3126_{{sublimetext_arch}}.deb dest={{sublimetext_tmp_deb}}"
  tags: ["packages","sublimetext"]

- name: Install sublimetext for Debian family OS
  apt: deb={{sublimetext_tmp_deb}}
  tags: ["packages","sublimetext"]

# Base16 
- name: base16 - checkout repo
  git:
    repo: https://github.com/chriskempson/base16-gnome-terminal.git
    dest: "/home//setup/base16-gnome"

- name: base16 - copy monokai-dark
  copy:
    src: "/home//setup/base16-gnome/base16-monokai.dark.sh"
    dest: "/home//base16-monokai.dark.sh"
    mode: 0755

- name: base16 - install monokai dark
  command: "/home//base16-monokai.dark.sh"

# - name: base16 - set system font to source code pro
#   gconftool-2:
#     key: /apps/gnome-terminal/profiles/base-16-monokai-dark/font
#     string: "Source Code Pro Semi-Bold 12"

# - name: base16 - dont use default system font in terminal
#   gconftool-2:
#     key: /apps/gnome-terminal/profiles/base-16-monokai-dark/use_system_font
#     bool: false

# - name: base16 - set default terminal profile
#   gconftool-2:
#     key: /apps/gnome-terminal/global/default_profile
#     string: "base-16-monokai-dark"

# - name: base-16 - get base16-shell so that colors show up correctly in vim
#   git:
#     repo: https://github.com/chriskempson/base16-shell.git
#     dest: "/home//.config/base16-shell"

# - name: Copy PhpStorm Programs folder
#   command: cp -rf /vagrant/private/PhpStorm/Programs /home/vagrant

- name: Copy PhpStorm Programs folder
  command: cp -rf /vagrant/private/PhpStorm2016.1/Programs /home/vagrant

- name: Copy PhpStorm .PhpStorm2016.1 folder
  command: cp -rf /vagrant/private/PhpStorm2016.1/.PhpStorm2016.1 /home/vagrant

- name: Copy PhpStorm .java folder
  command: cp -rf /vagrant/private/PhpStorm2016.1/.java /home/vagrant

- name: Copy phpstorm.desktop 
  copy: 
    src: ../private/PhpStorm2016.1/PhpStorm2016.desktop
    dest: /home/vagrant/Desktop 
    force: yes
    mode: 0777