---
- hosts: lamp
  become: yes
  # become_method: sudo
  # become_user: root
  # sudo: true
  gather_facts: true

  vars_files:
    - vars/main.yml

  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - geerlingguy.apache
    - geerlingguy.mysql
    - quan.php-5-6
    # - geerlingguy.php_downloaded
    # - geerlingguy.php
    # - { role: Aplyca.PHP }
    # - ansible-role-php
    # - aplyca.ansible-role-php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    # - geerlingguy.drupal
    # - ansible-phpstorm
    - ansible-role-phpstorm
    # - desktop
  #   - role: jdauphant.sublimetext

  tasks:
    - name: Installing something
      apt: "name={{ item }} state=installed"
      with_items:
      - git 
      - dos2unix 

    - name: Installing common package
      apt: "name={{ item }} state=installed"
      with_items: "{{ common_packages }}"

    - include: tasks/desktop_app.yml

    - include: ../private/web_work_setup.yml

    - include: tasks/remove_app.yml

    # - name: Copy and Execute the script 
      # script: ../scripts/ubuntu_settings.sh

    - name: Transfer the script
      copy: src=../scripts/ubuntu_settings.sh dest=/home/vagrant mode=0777

    - name: Convert the script
      command: dos2unix /home/vagrant/ubuntu_settings.sh

    - name: Execute the script
      command: sh /home/vagrant/ubuntu_settings.sh

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted


